defaults: &defaults
  google_tracking_id: UA-110694482-1
  site_url: https://japan-twilio-users.group/

development:
  <<: *defaults
  site_url: http://localhost:9999/

test:
  <<: *defaults
  site_url: http://localhost:9999/

production:
  <<: *defaults

